language: scala

scala:
  - 2.10.5
  - 2.11.6

script:
  - SPARK_VERSION="1.3.0" sbt ++$TRAVIS_SCALA_VERSION test
  - SPARK_VERSION="1.4.0" sbt ++$TRAVIS_SCALA_VERSION test
  - SPARK_VERSION="1.5.0" sbt ++$TRAVIS_SCALA_VERSION test
  - SPARK_VERSION="1.6.0" sbt ++$TRAVIS_SCALA_VERSION clean coverage test

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2

after_success:
  - pip install --user codecov && codecov
